FROM continuumio/anaconda3:latest
WORKDIR /usr/local/cellrp

# Install the dependencies
RUN apt-get update && apt-get install -y \
    git wget curl vim build-essential cmake && \
    rm -rf /var/lib/apt/lists/*